### ISSUE TITLE
Run .ev3 files on ev3Dev

### ISSUE THREAD

**Issue by jabrena** [ev3dev/lms2012-compat#34]
Hi @dlech, 

I was reading a bit this project and I would like to know if in some moment, the development will allow execute .ev3 files on the same environment of ev3dev.

Juan Antonio

**Comment by dlech** [comment]
.ev3 files are what is used on the official desktop software from LEGO, so no, .ev3 files will not run on ev3dev.

.rbf files are what will run on this software. But this is for BeagleBone only for now. Unless someone wants to fix #28, it will stay that way.

**Comment by jabrena** [comment]
but if the user could transform a .ev3 into .rbf, is a beginning.
https://sites.google.com/site/ev3basic/ev3-explorer

it could be very interesting to run in a EV3 or a Raspi, .rbf files (previously .ev3)

**Comment by WasabiFan** [comment]
@jabrena the user can, using LEGO's official software. The point is that .ev3 is the type of file their editor opens and .rbf is what it produces. What @dlech is saying is that this software (which makes ev3dev act like the official EV3 OS) that he is working on is only built to run on the BeagleBone because that is what he was asked to get working.  If someone else wants to modify it to make it compatible with other ev3dev platforms, they can.
