### ISSUE TITLE
Issue running sudo lms2012

### ISSUE THREAD

**Issue by pipothy** [ev3dev/lms2012-compat#63]
Hi,

Just booted into LMS2012 compat mode and ran sudo lms2012. I was greeted with the following problem:

![hidg0 error](https://user-images.githubusercontent.com/6817670/28727198-e0d428dc-73bb-11e7-9894-2de2c7ac2fa5.png)

The first time this happened, it was just the first line. The second time, it was both lines displayed there. The robot made the startup noise for the Lego Mindstorms' original software and then made some white noise.

Any idea why this might be? Couldn't find anything like it in the issues except some connectivity concerns, hence I moved it very close to the router second time to ensure it wasn't an unreliable connection.

EDIT: Close the issue, I'm a fool. It worked, but it was just being incredibly slow. Apologies!

**Comment by pipothy** [comment]
Just to check, I am getting the terminal saying "Failed to open PCM Playback: Device or resource busy" constantly and the screen on the EV3 keeps changing back to the screen for EV3Dev's boot. Is this normal, or is this related to the above issue? Sorry for the constant bothering!

**Comment by dlech** [comment]
* Failed to open /dev/hig0 problem: I noticed this too. I haven't look into it yet, but it probably means that you won't be able to use USB.

* Failed to create TCP listener problem: Is it possible you have two instances of `lms2012` running at the same time?

* White noise problem: The ev3dev sound driver needs some work. This is a general ev3dev problem, so please open an issue at <https://github.com/ev3dev/ev3dev/issues>.

* Failed to open PCM Playback: Device or resource busy problem: This also sounds like it could be caused by two instances of `lms2012` running.

* EV3 keeps changing back to the screen for EV3Dev's boot problem: Known issue, #60

**Comment by pipothy** [comment]
You're correct, USB cable wouldn't have the brick recognised on the official software. Any other way of getting the files over rather than the official program for now? Otherwise, I'll wait til it's fixed!

**Comment by dlech** [comment]
Bluetooth or Wi-Fi (or wired USB Ethernet dongle).

**Comment by dlech** [comment]
USB should be fixed with v1.99.5. (LEDs will be broken with this version until I do a kernel release.)

**Comment by dlech** [comment]
Kernel has been released. There should also be a snapshot image with these updates available in a couple hours.
